language: go
go:
- 1.13.x
services:
- docker

install:
- curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
  | sh -s -- -b $(go env GOPATH)/bin v1.23.8
script:
- "$(go env GOPATH)/bin/golangci-lint run"
# - TESTRUN=true go test -v -race ./...
- docker build -f Dockerfile -t betorvs/secretreceiver:$COMMIT .
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push betorvs/secretreceiver:$COMMIT
- docker tag betorvs/secretreceiver:$COMMIT betorvs/secretreceiver:latest
- docker push betorvs/secretreceiver:latest
