apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: secretreceiver
  annotations:
    github.com/project-slug: betorvs/secretreceiver
  links:
    - url: https://github.com/betorvs/secretpublisher
      title: Secret Publisher
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples