apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: secretreceiver
  annotations:
    github.com/project-slug: betorvs/secretreceiver
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples