apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: secretreceiver
  annotations:
    github.com/project-slug: betorvs/secretreceiver
  links:
    - url: https://github.com/betorvs/secretpublisher
      title: Secret Publisher
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
  dependsOn:
    - 'resource:kubernetes'
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kubernetes
  description: kubernetes to save secrets
spec:
  type: infrastructure
  owner: guests
  system: examples
